algoritmo "AT_03_AULA02"
// Disciplina  : ALGORITMOS E ESTRUTURA DE DADOS
// Professor   : PAULO LIMÍRIO DA SILVA
// Descrição   : Solicita a idade de uma pessoa e verifica se ela é maior ou menor de idade. 
// Autor(a)    : Antônio Murilo
// Data atual  : 17/03/2025

var

   age: inteiro

inicio

    escreva("Digite a sua idade: ")
    leia(age)

    se age >= 18 entao
        escreva("Maior de idade")
    senao
        escreva("Menor de idade")
    fimse

fimalgoritmo
