algoritmo "QUESTAO_01"
// Disciplina  : ALGORITMOS E ESTRUTURA DE DADOS
// Professor   : PAULO LIMÍRIO DA SILVA
// Descrição   : Declara variáveis para nome e idade, atribui valores e exibe uma frase formatada
// Autor(a)    : Antônio Murilo
// Data atual  : 29/05/2025

var
   name: caractere
   age: inteiro

inicio

   name <- "Antônio Murilo"
   age <- 23

   escreval("Meu nome é ", name, " e eu tenho ", age, " anos.")

fimalgoritmo
