algoritmo "QUESTAO_2"
// Disciplina  : ALGORITMOS E ESTRUTURA DE DADOS
// Professor   : PAULO LIMÍRIO DA SILVA
// Descrição   : Calcula a área de um círculo usando PI como constante
// Autor(a)    : Antônio Murilo
// Data atual  : 18/06/25


var
   r, a, p : real

inicio

   p <- 3.14159
   escreva("Digite o valor do raio do círculo: ")
   leia(raio)

   a <- p * r * r

   escreval("A área do círculo é: ", area:0:2)

fimalgoritmo
