algoritmo "QUESTAO_8"
// Disciplina  : ALGORITMOS E ESTRUTURA DE DADOS
// Professor   : PAULO LIMÍRIO DA SILVA
// Descrição   : Exibe números de 1 até o número digitado usando ENQUANTO
// Autor(a)    : Antônio Murilo
// Data atual  : 18/06/25

var
   number, i: inteiro

inicio
   escreva("Digite um número inteiro positivo: ")
   leia(number)

   i <- 1
   enquanto i <= number faca
      escreval(i)
      i <- i + 1
   fimenquanto

fimalgoritmo
