algoritmo "QUESTAO_9"
// Disciplina  : ALGORITMOS E ESTRUTURA DE DADOS
// Professor   : PAULO LIMÍRIO DA SILVA
// Descrição   : Solicita número par usando estrutura REPITA
// Autor(a)    : Antônio Murilo
// Data atual  : 18/06/25

var
   number: inteiro

inicio
   repita
      escreva("Digite um número par: ")
      leia(number)
   ate (number % 2 = 0)

   escreval("Obrigado! Você digitou um número par: ", number)

fimalgoritmo
