algoritmo "QUESTAO_25"
// Disciplina  : ALGORITMOS E ESTRUTURA DE DADOS
// Professor   : PAULO LIMÍRIO DA SILVA
// Descrição   : Contagem regressiva até 0
// Autor(a)    : Antônio Murilo
// Data atual  : 18/06/25

var
   startNum: inteiro

inicio
   escreva("Digite um número inteiro: ")
   leia(startNum)

   enquanto startNum >= 0 faca
      escreval(startNum)
      startNum <- startNum - 1
   fimenquanto

fimalgoritmo
