algoritmo "AT_02_AULA02"
// Disciplina  : ALGORITMOS E ESTRUTURA DE DADOS
// Professor   : PAULO LIMÍRIO DA SILVA
// Descrição   : Solicita a idade de uma pessoa e verifica se ela é maior de idade
// Autor(a)    : Antônio Murilo
// Data atual  : 17/03/2025

var

   age: inteiro

inicio

    escreva("Digite a sua idade: ")
    leia(age)

    se age >= 18 entao
        escreval("Sua idade: ", age)
        escreval("Você é maior de idade.")
    fimse

fimalgoritmo
